In [50]:
import torch
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from utils import load_embeddings

In [ ]:
ids, embeddings, metadata = load_embeddings('/home/ubuntu/dev/detoxify/jigsaw-toxic-comment-classification-challenge/data/embeddings_bart_test.pkl')

In [34]:
labels = pd.read_csv('/home/ubuntu/dev/detoxify/jigsaw-toxic-comment-classification-challenge/data/test_labels.csv', dtype={"id": "string"})
classes = list(labels.columns)
classes.remove("id")
y = labels[classes].to_numpy()
y

array([[-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       ...,
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1]])

In [69]:
mask = (y != -1).any(axis=1)
y_m = y[mask, :]
embeddings_m = embeddings[mask, :]
y_m.shape, embeddings_m.shape

X_train, X_test, y_train, y_test = train_test_split(embeddings_m, y_m, random_state=1)

In [70]:
clf = MLPClassifier(random_state=1, max_iter=300, verbose=True).fit(X_train, y_train)

Iteration 1, loss = 0.52424865
Iteration 2, loss = 0.39058075
Iteration 3, loss = 0.36288376
Iteration 4, loss = 0.34642276
Iteration 5, loss = 0.33375567
Iteration 6, loss = 0.32294132
Iteration 7, loss = 0.31072760
Iteration 8, loss = 0.30078304
Iteration 9, loss = 0.28499197
Iteration 10, loss = 0.27337345
Iteration 11, loss = 0.26328727
Iteration 12, loss = 0.24808044
Iteration 13, loss = 0.23355003
Iteration 14, loss = 0.22086999
Iteration 15, loss = 0.20593482
Iteration 16, loss = 0.19056859
Iteration 17, loss = 0.17915510
Iteration 18, loss = 0.16805109
Iteration 19, loss = 0.15676465
Iteration 20, loss = 0.14582459
Iteration 21, loss = 0.13319141
Iteration 22, loss = 0.12117297
Iteration 23, loss = 0.11091013
Iteration 24, loss = 0.10266433
Iteration 25, loss = 0.09486091
Iteration 26, loss = 0.08722656
Iteration 27, loss = 0.08112904
Iteration 28, loss = 0.07242242
Iteration 29, loss = 0.06742240
Iteration 30, loss = 0.06382512
Iteration 31, loss = 0.05836049
Iteration 32, los

In [71]:
clf.predict_proba(X_test[:1]), clf.predict(X_test[:5, :]), clf.score(X_test, y_test)

(array([[1.6445278e-12, 1.7939822e-31, 4.0213230e-19, 3.8896814e-20,
         9.6413227e-18, 9.3125893e-26]], dtype=float32),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]),
 0.8925914348233823)

In [72]:
from model_eval.eval_predictions import evaluate

In [73]:
scores = clf.predict_proba(embeddings_m)

In [74]:
evaluate(scores, y_m)

{'auc_scores': [0.9878005010070975,
  0.9969886362687173,
  0.9889785343894436,
  0.992401245737871,
  0.989412258480658,
  0.9923052284682082],
 'mean_auc': 0.9913144007253326}